# Generated by Django 4.2.2 on 2023-06-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0002_post_title_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_tag',
            new_name='title_tags',
        ),
    ]
