# Generated by Django 4.2.2 on 2023-06-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0003_rename_title_tag_post_title_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tags',
            field=models.CharField(default='This is a blog Web App!!', max_length=250),
        ),
    ]
