# Generated by Django 4.1.7 on 2023-06-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0004_alter_post_title_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tags',
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='This is a blog Web App!', max_length=250),
        ),
    ]
