# Generated by Django 4.2.2 on 2023-06-10 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0005_remove_post_title_tags_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
