# Generated by Django 4.1.7 on 2023-06-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0011_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
