# Generated by Django 4.1.7 on 2023-06-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0012_post_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='header_images',
        ),
    ]
