# Generated by Django 4.1.7 on 2023-06-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0013_rename_header_image_post_header_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_images',
            new_name='header_image',
        ),
    ]
