# Generated by Django 4.1.7 on 2023-06-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0014_rename_header_images_post_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='upload_image',
        ),
    ]
