# Generated by Django 4.2.2 on 2023-06-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0017_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
