# Generated by Django 4.2.2 on 2023-06-27 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_folder', '0020_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='Blog_Post', to=settings.AUTH_USER_MODEL),
        ),
    ]
