# Generated by Django 4.2.2 on 2023-06-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0022_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click to View The Post', max_length=255),
        ),
    ]
