# Generated by Django 4.1.7 on 2023-06-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0024_alter_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click to View Post', max_length=255),
        ),
    ]
