# Generated by Django 4.1.7 on 2023-07-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0025_alter_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Technology', max_length=255),
        ),
    ]
